# Ai-du Project

# Project information
site_name: 'AI-EDU'
site_author: 'AI-Edu Team'
site_description: '微软人工智能教育与学习共建社区(简称AI_Edu)是一个涵盖人工智能、深度学习等内容的开源知识社区，帮助用户在学与实践中掌握人工智能的知识。'
copyright: 'Copyright © Microsoft Corporation. All rights reserved.'
repo_name: Microsoft/ai-edu
repo_url: 'https://github.com/microsoft/ai-edu'
use_directory_urls: false

# Configuration
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  font:
    text: Roboto
    code: Roboto Mono
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - header.autohide

# Plugins
plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: true

# Page tree
nav:
  - Ai-edu: 'index.md'
  - 基础教程:
    - 本页介绍: './基础教程/README.md'
    - 神经网络基本原理:
      - 本课介绍: './基础教程/A2-神经网络基本原理/README.md'
      - 第一步、基本知识:
        - 00 前言: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/00 前言.md'
        - 01 概论与基本概念: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/01 第一步 - 概论与基本概念.md'
        - 01.0 人工智能发展简史: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/01.0-人工智能发展简史.md'
        - 01.2 人工智能的定义: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/01.1-人工智能的定义.md'
        - 01.2 范式的演化: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/01.2-范式的演化.md'
        - 01.3 神经网络的基本工作原理: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/01.3-神经网络的基本工作原理.md'
        - 02.0 反向传播与梯度下降: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/02.0-反向传播与梯度下降.md'
        - 02.1 线性反向传播: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/02.1-线性反向传播.md'
        - 02.2 非线性反向传播: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/02.2-非线性反向传播.md'
        - 02.3 梯度下降: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/02.3-梯度下降.md'
        - 03.0 损失函数: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/03.0-损失函数.md'
        - 03.1 均方差损失函数: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/03.1-均方差损失函数.md'
        - 03.2 交叉熵损失函数: './基础教程/A2-神经网络基本原理/第1步 - 基本知识/03.2-交叉熵损失函数.md'
      - 第二步、线性回归:
        - 04 线性回归: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/04 第二步 - 线性回归.md'
        - 04.0 单变量线性回归: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/04.0-单入单出单层-单变量线性回归.md'
        - 04.1 最小二乘法: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/04.1-最小二乘法.md'
        - 04.2 梯度下降法: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/04.2-梯度下降法.md'
        - 04.3 神经网络法: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/04.3-神经网络法.md'
        - 04.4 多样本计算: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/04.4-多样本计算.md'
        - 04.5 梯度下降的三种形式: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/04.5-梯度下降的三种形式.md'
        - 05.0 多变量线性回归: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/05.0-多入单出单层-多变量线性回归.md'
        - 05.1 正规方程法: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/05.1-正规方程法.md'
        - 05.2 神经网络法: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/05.2-神经网络法.md'
        - 05.3 样本特征数据标准化: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/05.3-样本特征数据标准化.md'
        - 05.4 还原参数值: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/05.4-还原参数值.md'
        - 05.5 正确的推理方法: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/05.5-正确的推理方法.md'
        - 05.6 标准化标签值: './基础教程/A2-神经网络基本原理/第2步 - 线性回归/05.6-标准化标签值.md'
      - 第三步、线性分类:
        - 06 线性分类: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/06 第三步 - 线性分类.md'
        - 06. 线性二分类: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/06.0-多入单出单层神经网络-线性二分类.md'
        - 06.1 二分类函数: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/06.1-二分类函数.md'
        - 06.2 线性二分类实现: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/06.2-线性二分类实现.md'
        - 06.3 线性二分类的工作原理: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/06.3-线性二分类的工作原理.md'
        - 06.4 线性二分类结果可视化: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/06.4-线性二分类结果可视化.md'
        - 06.5 实现逻辑与或非门: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/06.5-实现逻辑与或非门.md'
        - 06.6 用双曲正切函数分类: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/06.6-用双曲正切函数分类.md'
        - 07.0 线性多分类: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/07.0-多入多出单层神经网络-线性多分类.md'
        - 07.1 多分类函数: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/07.1-多分类函数.md'
        - 07.2 线性多分类实现: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/07.2-线性多分类实现.md'
        - 07.3 线性多分类的工作原理: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/07.3-线性多分类的工作原理.md'
        - 07.4 线性多分类结果可视化: './基础教程/A2-神经网络基本原理/第3步 - 线性分类/07.4-线性多分类结果可视化.md'
      - 第四步、非线性回归:
        - 08 非线性回归: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/08 第四步 - 非线性回归.md'
        - 08.0 激活函数: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/08.0-激活函数.md'
        - 08.1 挤压型激活函数: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/08.1-挤压型激活函数.md'
        - 08.2 半线性激活函数: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/08.2-半线性激活函数.md'
        - 09.0 非线性回归: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/09.0-单入单出双层-非线性回归.md'
        - 09.1 多项式回归法拟合正弦曲线: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/09.1-多项式回归法拟合正弦曲线.md'
        - 09.2 多项式回归法拟合复合函数曲线: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/09.2-多项式回归法拟合复合函数曲线.md'
        - 09.3 验证与测试: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/09.3-验证与测试.md'
        - 09.4 神经网络非线性回归的实现: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/09.4-神经网络非线性回归的实现.md'
        - 09.5 曲线拟合: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/09.5-曲线拟合.md'
        - 09.6 非线性回归的工作原理: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/09.6-非线性回归的工作原理.md'
        - 09.7 参数调优初步: './基础教程/A2-神经网络基本原理/第4步 - 非线性回归/09.7-参数调优初步.md'
      - 第五步、非线性分类:
        - 10 非线性分类: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/10 第五步 - 非线性分类.md'
        - 10.0 非线性二分类: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/10.0-多入单出双层-非线性二分类.md'
        - 10.1 为什么必须用双层神经网络: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/10.1-为什么必须用双层神经网络.md'
        - 10.2 非线性二分类实现: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/10.2-非线性二分类实现.md'
        - 10.3 实现逻辑异或门: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/10.3-实现逻辑异或门.md'
        - 10.4 逻辑异或门的工作原理: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/10.4-逻辑异或门的工作原理.md'
        - 10.5 实现双弧形二分类: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/10.5-实现双弧形二分类.md'
        - 10.6 双弧形二分类的工作原理: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/10.6-双弧形二分类的工作原理.md'
        - 11.0 非线性多分类: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/11.0-多入多出双层-非线性多分类.md'
        - 11.1 非线性多分类实现: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/11.1-非线性多分类实现.md'
        - 11.2 非线性多分类的工作原理: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/11.2-非线性多分类的工作原理.md'
        - 11.3 分类样本不平衡问题: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/11.3-分类样本不平衡问题.md'
        - 12.0  多变量非线性分类: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/12.0-多入多出三层-多变量非线性分类.md'
        - 12.1 三层神经网络的实现: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/12.1-三层神经网络的实现.md'
        - 12.2 梯度检查: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/12.2-梯度检查.md'
        - 12.3 学习率与批大小: './基础教程/A2-神经网络基本原理/第5步 - 非线性分类/12.3-学习率与批大小.md'
      - 第六步、模型部署:
        - 13 模型的推理与部署: './基础教程/A2-神经网络基本原理/第6步 - 模型部署/13 第六步 - 模型的推理与部署.md'
        - 13.0 手工测试训练效果: './基础教程/A2-神经网络基本原理/第6步 - 模型部署/13.0-手工测试训练效果.md'
        - 13.1 模型文件概述: './基础教程/A2-神经网络基本原理/第6步 - 模型部署/13.1-模型文件概述.md'
        - 13.2 ONNX模型文件: './基础教程/A2-神经网络基本原理/第6步 - 模型部署/13.2-ONNX模型文件.md'
        - 13.3 Windows中模型的部署: './基础教程/A2-神经网络基本原理/第6步 - 模型部署/13.3-Windows中模型的部署.md'
      - 第七步、深度神经网络:
        - 14 深度神经网络: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/14 第七步 - 深度神经网络.md'
        - 14.0 搭建深度神经网络框架: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/14.0-搭建深度神经网络框架.md'
        - 14.1 回归任务功能测试: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/14.1-回归任务功能测试.md'
        - 14.2 回归任务真实案例: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/14.2-回归任务真实案例.md'
        - 14.3 二分类任务功能测试: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/14.3-二分类任务功能测试.md'
        - 14.4 二分类任务真实案例: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/14.4-二分类任务真实案例.md'
        - 14.5 多分类任务功能测试: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/14.5-多分类任务功能测试.md'
        - 14.6多分类任务真实案例: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/14.6-多分类任务真实案例.md'
        - 15.0 网络优化: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/15.0-网络优化.md'
        - 15.1 权重矩阵初始化: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/15.1-权重矩阵初始化.md'
        - 15.2 梯度下降优化算法: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/15.2-梯度下降优化算法.md'
        - 15.3 自适应学习率算法: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/15.3-自适应学习率算法.md'
        - 15.4 算法效果比较: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/15.4-算法效果比较.md'
        - 15.5 批量归一化的原理: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/15.5-批量归一化的原理.md'
        - 15.6 批量归一化的实现: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/15.6-批量归一化的实现.md'
        - 16.0 正则化: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/16.0-正则化.md'
        - 16.1 偏差与方差: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/16.1-偏差与方差.md'
        - 16.2 L2正则: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/16.2-L2正则.md'
        - 16.3 L1正则: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/16.3-L1正则.md'
        - 16.4 早停法: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/16.4-早停法.md'
        - 16.5 丢弃法: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/16.5-丢弃法.md'
        - 16.6 数据扩展: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/16.6-数据扩展.md'
        - 16.7 集成学习: './基础教程/A2-神经网络基本原理/第7步 - 深度神经网络/16.7-集成学习.md'
      - 第八步、卷积神经网络:
        - 17 卷积神经网络: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/17 第八步 - 卷积神经网络.md'
        - 17.0 卷积神经网络原理: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/17.0-卷积神经网络原理.md'
        - 17.1 卷积的前向计算原理: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/17.1-卷积的前向计算原理.md'
        - 17.2 卷积前向计算代码实现: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/17.2-卷积前向计算代码实现.md'
        - 17.3 卷积的反向传播原理: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/17.3-卷积的反向传播原理.md'
        - 17.4 卷积反向传播代码实现: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/17.4-卷积反向传播代码实现.md'
        - 17.5 池化的前向计算与反向传播: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/17.5-池化的前向计算与反向传播.md'
        - 18.0 经典卷积神经网络模型: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/18.0-经典卷积神经网络模型.md'
        - 18.1 实现颜色分类: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/18.1-实现颜色分类.md'
        - 18.2 实现几何图形分类: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/18.2-实现几何图形分类.md'
        - 18.3 实现几何图形及颜色分类: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/18.3-实现几何图形及颜色分类.md'
        - 18.4 MNIST分类: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/18.4-MNIST分类.md'
        - 18.5 Fashion-MNIST分类: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/18.5-Fashion-MNIST分类.md'
        - 18.6 Cifar-10分类: './基础教程/A2-神经网络基本原理/第8步 - 卷积神经网络/18.6-Cifar-10分类.md'
      - 第九步、循环神经网络:
        - 19 循环神经网络: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/19 第九步 - 循环神经网络.md'
        - 19.0 普通循环神经网络: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/19.0-普通循环神经网络.md'
        - 19.1 两个时间步的循环神经网络: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/19.1-两个时间步的循环神经网络.md'
        - 19.2 四个时间步的循环神经网络: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/19.2-四个时间步的循环神经网络.md'
        - 19.3 通用的循环神经网络模型: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/19.3-通用的循环神经网络模型.md'
        - 19.4 空气质量预测: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/19.4-空气质量预测.md'
        - 19.5 不定长时序的循环神经网络: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/19.5-不定长时序的循环神经网络.md'
        - 19.6 深度循环神经网络: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/19.6-深度循环神经网络.md'
        - 19.7 双向循环神经网络: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/19.7-双向循环神经网络.md'
        - 20.0 高级循环神经网络: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/20.0-高级循环神经网络.md'
        - 20.1 LSTM基本原理: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/20.1-LSTM基本原理.md'
        - 20.2 LSTM代码实现: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/20.2-LSTM代码实现.md'
        - 20.3 GRU基本原理: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/20.3-GRU基本原理.md'
        - 20.4 序列到序列: './基础教程/A2-神经网络基本原理/第9步 - 循环神经网络/20.4-序列到序列.md'
    - 人工智能系统:
      - 本课介绍: "./基础教程/A6-人工智能系统/README.md"
      - 课程目录: "./基础教程/A6-人工智能系统/Lectures/README.md"
      - 实验:
        - 1. 框架及工具入门示例: "./基础教程/A6-人工智能系统/Labs/BasicLabs/Lab1/README.md"
        - 2. 定制一个新的张量运算: "./基础教程/A6-人工智能系统/Labs/BasicLabs/Lab2/README.md"
        - 3. CUDA实现和优化: "./基础教程/A6-人工智能系统/Labs/BasicLabs/Lab3/README.md"
        - 4 AllReduce的实现和优化: "./基础教程/A6-人工智能系统/Labs/BasicLabs/Lab4/README.md"
        - 5. 配置Container进行云上训练或推理: "./基础教程/A6-人工智能系统/Labs/BasicLabs/Lab5/README.md"
        - 6. 学习使用调度管理系统: "./基础教程/A6-人工智能系统/Labs/AdvancedLabs/Lab6/README.md"
        - 7. 分布式训练任务练习: "./基础教程/A6-人工智能系统/Labs/AdvancedLabs/Lab7/README.md"
        - 8 自动机器学习系统练习: "./基础教程/A6-人工智能系统/Labs/AdvancedLabs/Lab8/README.md"
        - 9 强化学习系统练习: "./基础教程/A6-人工智能系统/Labs/AdvancedLabs/Lab9/README.md"
  - 实践案例:
    - 本页介绍: './实践案例/README.md'
    - 1.漫画翻译: './实践案例/B01-漫画翻译/README.md'
    - 2.问答系统和对话机器人服务: './实践案例/B02-问答系统和对话机器人服务/README.md'
    - 3.看图识熊: './实践案例/B03-看图识熊/README.md'
    - 4.智能家居: './实践案例/B04-智能家居/README.md'
    - 5.文本朗读应用: './实践案例/B05-文本朗读应用/README.md'
    - 6.搭建中间服务层: './实践案例/B06-搭建中间服务层/README.md'
    - 7.手写数字识别: './实践案例/B07-手写数字识别/README.md'
    - 8.黄金点游戏: './实践案例/B08-黄金点游戏/README.md'
    - 9.手写算式计算器: './实践案例/B09-手写算式计算器/README.md'
    - 10.机器学习平台建设: './实践案例/B10-机器学习平台建设/README.md'
    - 11.量化交易案例: './实践案例/B11-量化交易案例/README.md'
    - 12.基于近邻图的向量搜索案例: './实践案例/B12-基于近邻图的向量搜索案例/README.md'
    - 13.AI对联生成案例: './实践案例/B13-AI对联生成案例/README.md'
    - 14.快速构建中文文本蕴含深度学习模型: './实践案例/B14-快速构建中文文本蕴含深度学习模型/README.md'
    - 15.基于深度学习的代码搜索案例: './实践案例/B15-基于深度学习的代码搜索案例/README.md'
    - 16.基于LightGBM的时间序列预测: './实践案例/B16-基于LightGBM的时间序列预测/README.md'
  - 最新动态: 'News.md'
  - 关于我们: 
    - 'about.md'
    - License: 'LICENSE.md'

# Extra CSS

# Extra javascript
extra_javascript:
  - javascripts/config.js
  - https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.12.1/polyfill.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml.min.js


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - meta
  - footnotes
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
